# RcppMeCab

on: workflow_dispatch

name: build-rcppmecab

jobs:
  rcppmecab:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install Japanese MeCab for Ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8
      - name: Clone repo
        run: |
          git clone --depth 1 https://github.com/paithiov909/RcppMeCab.git
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: RcppMeCab
          extra-packages: |
            any::drat
            any::pkgbuild
      - name: Insert package
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e "pkg <- pkgbuild::build('RcppMeCab', binary = TRUE, quiet = TRUE); drat::insertPackage(pkg, commit = TRUE)"
