# RcppMeCab-ubuntu

on: workflow_dispatch

name: build-rcppmecab

jobs:
  rcppmecab:
    strategy:
      matrix:
        platform: [windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Install Japanese MeCab for Ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8
      - name: Clone repo
        run: |
          git clone --depth 1 https://github.com/paithiov909/RcppMeCab.git
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          working-directory: RcppMeCab
          extra-packages: |
            any::drat
            any::git2r
            any::pkgbuild
      - name: Insert package
        env:
          GITHUB_ACTOR: ${{ github.actor }}
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          Rscript -e "options(dratBranch = 'docs'); pkg <- pkgbuild::build('RcppMeCab', dest_path = tempdir(), binary = TRUE, quiet = TRUE); drat::insertPackage(pkg, repodir = '.', commit = TRUE)"
          Rscript -e "options(dratBranch = 'docs'); pkg <- pkgbuild::build('RcppMeCab', dest_path = tempdir(), binary = FALSE, quiet = TRUE); drat::insertPackage(pkg, repodir = '.', commit = TRUE)"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          delete-branch: true
