# RcppMeCab

on: workflow_dispatch

name: build-rcppmecab

jobs:
  strategy:
    matrix:
      platform: [ubuntu-latest, windows-latest]
  rcppmecab:
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: Install Japanese MeCab for Ubuntu
        if: ${{ matrix.platform == 'ubuntu-latest' }}
        run: |
          sudo apt install mecab libmecab-dev mecab-ipadic-utf8
      - name:
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git clone --depth 1 https://github.com/paithiov909/RcppMeCab.git
          Rscript -e "pkg <- pkgbuild::build('RcppMeCab', binary = TRUE, quiet = TRUE); drat::insertPackage(pkg, commit = TRUE)"
